# Generated by Django 6.0.2 on 2026-03-13 19:29

from django.db import migrations


def set_admin_password(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    try:
        admin_user = User.objects.get(email='admin@mineiro.com')
        admin_user.set_password('Monteiro03_')
        admin_user.save()
    except User.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_nome_completo'),
    ]

    operations = [
        migrations.RunPython(set_admin_password),
    ]
