# Generated by Django 6.0.2 on 2026-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='whatsapp_bot_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave Bot WhatsApp'),
        ),
    ]
