# Generated by Django 6.0.2 on 2026-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barbeiro_whatsapp_bot_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
